import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { TheHeader } from "../../../components/common/Header/TheHeader";
import { TheFooter } from "../../../components/common/Footer/TheFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: "ru" | "en" | "uk";
  };
};

const RootLayout: React.FC<Props> = ({ children, params: {locale} }) => {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={inter.className}>
        <NextIntlClientProvider  messages={messages}>
          <TheHeader />
          {children}
          <TheFooter />
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
